version: 0.2
env:
  variables:
    APP_NAME: "fse4-skill-tracker-app"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      # - ng build --configuration=production
      - ng build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://fse4-sudheer-st-app-files --delete
